services:
  web:
    image: nginx
    ports:
      - 81:80
    volumes:
      - /home/dasha/projects/online-shop/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/dasha/projects/online-shop:/var/www/html
  php-fpm:
    image: php:8.1-fpm
    build: dasha/env
    volumes:
      - /home/dasha/projects/online-shop:/var/www/html
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 54322:5432




